# Generated by Django 3.0.5 on 2020-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("customer", "customer"), ("manager", "manager")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
